In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
data = load_diabetes()

In [3]:
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [5]:
x=data.data
y=data.target

In [6]:
x,y

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
   

In [7]:
import pandas as pd

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [19]:
x_train.shape

(353, 10)

In [20]:
x_test.shape

(89, 10)

In [21]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [22]:
lr.fit(x_train,y_train)

LinearRegression()

In [23]:
pred = lr.predict(x_test)
pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [24]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [25]:
from sklearn.metrics import r2_score,mean_squared_error
mse = mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)
print("Mean Squared Error:",mse)
print("R2 Score:",r2)

Mean Squared Error: 3094.4566715660626
R2 Score: 0.4399338661568968


In [26]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [27]:
lr.intercept_

np.float64(151.88331005254167)

# **Multiple Linear Regression Model From Scratch**

In [45]:
class mylr:
  def __inti__(self):
    self.coef_=None
    self.intercept_=None
  def fit(self,x_train,y_train):

    # addition of 1 as first column in x_train
    x_train=np.insert(x_train,0,1,axis=1)

    #coefficients finding
    betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(np.dot(x_train.T,y_train))
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict(self,x_test):
    return (np.dot(x_test,self.coef_)+self.intercept_)

In [46]:
multipleLr = mylr()

In [47]:
multipleLr.fit(x_train,y_train)

In [52]:
prediction =  multipleLr.predict(x_test)

In [53]:
prediction

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [54]:
mse = mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)
print("Mean Squared Error:",mse)
print("R2 Score:",r2)

Mean Squared Error: 3094.4566715660626
R2 Score: 0.4399338661568968
